// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7wWai6dcC9BtdhaHpQlKFQ4FvQKCyJUE',
    appId: '1:448618578101:web:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'safealert-demo',
    authDomain: 'safealert-demo.firebaseapp.com',
    storageBucket: 'safealert-demo.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrZ-HjbGp1f4NH4kBhcUo',
    appId: '1:448618578101:android:52d3ac3164627259ac3efc',
    messagingSenderId: '448618578101',
    projectId: 'safealert-demo',
    storageBucket: 'safealert-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7wWai6dcC9BtdhaHpQlKFQ4FvQKCyJUE',
    appId: '1:448618578101:ios:f1bf01e79ab2d2b9ac3efc',
    messagingSenderId: '448618578101',
    projectId: 'safealert-demo',
    storageBucket: 'safealert-demo.appspot.com',
    iosBundleId: 'com.example.safealert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7wWai6dcC9BtdhaHpQlKFQ4FvQKCyJUE',
    appId: '1:448618578101:ios:f1bf01e79ab2d2b9ac3efc',
    messagingSenderId: '448618578101',
    projectId: 'safealert-demo',
    storageBucket: 'safealert-demo.appspot.com',
    iosBundleId: 'com.example.safealert',
  );
}